
import static com.sun.xml.internal.ws.api.config.management.policy.ManagementAssertion.Setting.ON;
import java.awt.event.ActionListener;
import static javax.swing.DropMode.ON;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author CC
 */
public class Menu extends javax.swing.JFrame {
    AddStudent Add=new AddStudent();
    Display_All_Student Display=new Display_All_Student();
    RemoveStudent Remove= new RemoveStudent();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        Show_Button = new javax.swing.JCheckBox();
        btnAdd = new javax.swing.JButton();
        btnDiplay = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 2, 11)); // NOI18N
        jLabel1.setText("Managing Student Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 170, 30));

        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 30));
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, 30));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, 30));

        Show_Button.setText("show password");
        Show_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_ButtonActionPerformed(evt);
            }
        });
        jPanel1.add(Show_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 140, -1));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 80, 40));

        btnDiplay.setText("Display");
        btnDiplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiplayActionPerformed(evt);
            }
        });
        jPanel1.add(btnDiplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 70, 40));

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel1.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 90, 40));

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 10, 50, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 17, 440, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
       if (txtUsername.equals("")){
           JOptionPane.showMessageDialog(null,"Please enter username");
        }
        else if (txtPassword.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Password");
        }
        else if(txtPassword.getText().contains("Admin1234")&&txtUsername.getText().contains("Admin")){
        JOptionPane.showMessageDialog(null,"Sucessully login");
        txtPassword.setText(" ");
        txtUsername.setText(" ");
        Remove.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null,"Wrong password or username","Message",JOptionPane.ERROR_MESSAGE);
        }
       this.dispose();
       // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtUsername.equals("")){
           JOptionPane.showMessageDialog(null,"Please enter username");
        }
        else if (txtPassword.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Password");
        }
        else if(txtPassword.getText().contains("Admin1234")&&txtUsername.getText().contains("Admin")){
        JOptionPane.showMessageDialog(null,"Sucessully login");
        txtPassword.setText("");
        txtUsername.setText(" ");
        Add.setVisible(true);
        Add.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        else{
        JOptionPane.showMessageDialog(null,"Wrong password or username","Message",JOptionPane.ERROR_MESSAGE);
        }
        
        
        this.dispose();
        
    // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void Show_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_ButtonActionPerformed
      if(Show_Button.isSelected()){
          txtPassword.setEchoChar((char)(0));
      }
      else{
      txtPassword.setEchoChar('*');
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_Show_ButtonActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnDiplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiplayActionPerformed
        if (txtUsername.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter username");
        }
        else if (txtPassword.equals("")){
            JOptionPane.showMessageDialog(null,"Please enter Password");
        }
        else if(txtPassword.getText().contains("Admin1234")&&txtUsername.getText().contains("Admin")){
            JOptionPane.showMessageDialog(null,"Sucessully login");
            txtPassword.setText(" ");
            txtUsername.setText(" ");
            Display.setVisible(true);
            Display.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        }
        else{
            JOptionPane.showMessageDialog(null,"Wrong password or username","Message",JOptionPane.ERROR_MESSAGE);
        }
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Show_Button;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDiplay;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    void addActionListener(ActionListener actionListener) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    void setText(String exit) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
